language: python

sudo: required

python:
    - "2.7"

services:
    - postgresql
    - redis-server

addons:
    postgresql: "9.4"

env:
    - CKANVERSION=master
    - CKANVERSION=2.8
    - CKANVERSION=2.7
    - CKANVERSION=2.6

install: bash travis/build.bash

script: bash travis/run.bash

after_success: coveralls

